### ISSUE TITLE
Larger Font

### ISSUE THREAD

**Issue by SupaFresh** [SupaFresh/AntiAdverb#2]
Have the font used in the program be bigger and easier to read.

**Comment by sudoursa** [comment]
This one isn't exactly fixed in your program itself.

Go to your python folder\Lib\site-packages\easygui and then open the easygui.py file in your text editor. If you scroll through that file it's very close to the top. You should see this in the code and you can just change it accordingly.

PROPORTIONAL_FONT_FAMILY = ("MS", "Sans", "Serif")
MONOSPACE_FONT_FAMILY    = ("Courier")

PROPORTIONAL_FONT_SIZE  = 10
MONOSPACE_FONT_SIZE     =  9 
TEXT_ENTRY_FONT_SIZE    = 12

**Comment by sudoursa** [comment]
Apparently sometimes the font settings are not in easygui.py, but rather in \Lib\site-packages\easygui\boxes\global_state.py like in my case...

**Comment by SupaFresh** [comment]
Ok thank you for the feedback!
